accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView
from .forms import PwdResetConfirmForm, PwdResetForm




app_name = 'accounts'

urlpatterns = [
    path('register/', views.register_user, name='register'),
    path('login/', views.user_login, name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='/accounts/login/'), name='logout'),
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name="account/password_reset.html", success_url='password_reset_successful', email_template_name='account/password_reset_email.html',form_class=PwdResetForm), name='password_reset'),
    path('password_reset_confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='account/password_reset_confirm.html'),name="password_reset_confirm"),
    path('password_reset/password_reset_successful',
         TemplateView.as_view(template_name="account/password_reset_done.html"), name='password_reset_successful'),
    path('accounts/reset/done/',
         TemplateView.as_view(template_name="account/reset_status.html"), name='password_reset_complete'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('profile/edit/', views.edit_profile, name='edit_profile'),
    path('profile/delete_user/', views.delete_profile, name='delete_profile'),
    path('profile/delete_confirm/', TemplateView.as_view(template_name="account/delete_profile.html"), name='confirm_delete'),
    path('order/checkout/', views.checkout, name='payment'),


    path('password_reset/password_reset_successful/password_reset_email_confirm/',
         TemplateView.as_view(template_name="account/password_reset_email.html"), name='password_reset_email'),
]

cart/urls.py
from django.urls import path
from . import views
from .views import CheckOut, Cart, Index, store
app_name = 'cart'
urlpatterns=[

    path('basket/', views.basket, name='basket' ),
    path('add/', views.add_basket, name='add_basket'),
    path('cart/', Cart.as_view() , name='cart'),
    path('checkouts/', CheckOut.as_view() , name='checkout'),
    path('basket/add_to_cart/', views.add_to_cart, name='add_to_cart'),
    ]

mystore/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls', namespace='shop')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('basket/', include('basket.urls', namespace='basket')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    ]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

payment/urls.py
from django.urls import path

from . import views

app_name = 'payment'

urlpatterns = [
    path('', views.BasketView, name='basket'),
    path('orderplaced/', views.order_placed, name='order_placed'),
    path('error/', views.Error.as_view(), name='error'),
    path('webhook/', views.stripe_webhook),
]

shop/urls.py
from django.urls import path
from  . import views
from .views import Index, store


app_name = 'shop'

urlpatterns = [
    path('', store , name='store'),
    path('index/', Index.as_view(), name='homepage'),

    path('<slug:slug>/', views.item_detail, name='item_detail'),
    path('shop/<slug:category_slug>/', views.category_list, name='category_list'),
]


# path('store/basket', basket , name='basket'),

shop/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User


# Create your models here.




class Category(models.Model):
    name = models.CharField(max_length=255, db_index=True)
    slug = models.SlugField(max_length=255, unique=True)

    class Meta:
        verbose_name_plural = 'categories'

    def get_absolute_url(self):
        return reverse('shop:category_list', args=[self.slug])

    @staticmethod
    def get_all_categories():
        return Category.objects.all()

    def __str__(self):
        return self.name

class Product(models.Model):
    category = models.ForeignKey(Category, related_name='product', on_delete=models.CASCADE)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE, related_name='product_creator')
    title = models.CharField(max_length=255, default='admin')
    description = models.TextField(blank=True)
    image = models.ImageField(upload_to='images/')
    slug = models.SlugField(max_length=255)
    price = models.DecimalField(max_digits=7, decimal_places=2)
    in_stock = models.BooleanField(default=True)
    is_active = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)


    class Meta:
        verbose_name_plural = 'Products'
        ordering = ('-created', '-updated')


    def get_absolute_url(self):
        return reverse('shop:item_detail', args=[self.slug])

    def __str__(self):
        return self.title

    def get_add_to_cart_url(self):
        return reverse("shop:item_detail", kwargs={
            'slug': self.slug
        })

    @staticmethod
    def get_products_by_id(ids):
        return Product.objects.filter (id__in=ids)

    @staticmethod
    def get_all_products():
        return Product.objects.all()

    @staticmethod
    def get_all_products_by_categoryid(category_id):
        if category_id:
            return Product.objects.filter (category=category_id)
        else:
            return Product.get_all_products();

shop/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Category, Product
from django.views import  View


#Create your views here.
# def all_items(request):
#     # query database for all objects in products table
#     products = Product.objects.all
#     # load the data on the associated template
#     return render(request, 'shop/home.html', {'products': products})
class Index(View):

    def post(self , request):
        product = request.POST.get('product')
        remove = request.POST.get('remove')
        cart = request.session.get('cart')
        if cart:
            quantity = cart.get(product)
            if quantity:
                if remove:
                    if quantity<=1:
                        cart.pop(product)
                    else:
                        cart[product]  = quantity-1
                else:
                    cart[product]  = quantity+1

            else:
                cart[product] = 1
        else:
            cart = {}
            cart[product] = 1

        request.session['cart'] = cart
        print('cart' , request.session['cart'])
        return redirect('homepage')



    def get(self , request):
        # print()
        return render(request , 'shop/home.html')

def store(request):
    products = None
    categories = Category.get_all_categories()
    categoryID = request.GET.get('category')
    if categoryID:
        products = Product.get_all_products_by_categoryid(categoryID)
    else:
        products = Product.get_all_products();

    data = {}
    data['products'] = products
    data['categories'] = categories

    return render(request, 'shop/home.html', data)

def categories(request):
    # collect and return all the category information from the category table
    return{
        'categories': Category.objects.all()
    }
# def basket(request):
#     cart = request.session.get('cart')
#     if not cart:
#         request.session['cart'] = {}
#     products = None
#     categories = Category.get_all_categories()
#     categoryID = request.GET.get('category')
#     if categoryID:
#         products = Product.get_all_products_by_categoryid(categoryID)
#     else:
#         products = Product.get_all_products();

    # data = {}
    # data['products'] = products
    # data['categories'] = categories

    # print('you are : ', request.session.get('email'))
    # return render(request, 'shop/home.html', data)


def item_detail(request, slug):
    # select from the products table, the item which slug equals slug
    product = get_object_or_404(Product, slug=slug, in_stock=True)
    return render(request, 'shop/item.html', {'product':product})


def category_list(request, category_slug):
    category = get_object_or_404(Category,slug=category_slug)
    # filter the products table by the category column
    products =  Product.objects.filter(category=category)
    return render(request, 'shop/category.html', {'category': category, 'products':products})

templates/shop/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
   <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700;800;900&display=swap"
    rel="stylesheet">
    <title>{%  block title %}
    Store{%  endblock %}
    </title>
    <style>
      @media only screen and (max-width: 700px) {
        .cat-img {
          max-width: 100%;
          height: auto;
          }
      }

    @media only screen and (min-width: 700px) {
        .item {
            margin-top: 5rem;
          }
      }


        /*body{*/
        /*    background: #F4D03F ;*/
        /*}*/
        .btn-nav {
            background-color: #F4D03F;
        }
        .btn-other{
          background-color: black;
        }
        .btn a{
          text-decoration: none;
          color:black;
        }

        .home-img {
          background-size: contain;
          max-width: 100%;
          height: auto;
        }

        .cat-img{
          display: block;
          margin-left: auto;
          margin-right: auto;
        }
        .item{
            margin-bottom: 10rem;
        }

      .footer{
        background-color: black;
      }


          </style>
  </head>
  <body>
  <header>
 <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">E-Store</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav">
        <a class="nav-link active" aria-current="page" href="{% url 'shop:store' %}">Home</a>
        <a class="nav-link active" href="{% url 'accounts:dashboard' %}">Dashboard</a>
        <a class="nav-link active" href="{% url 'accounts:payment' %}">Checkout</a>
        <!--       <li class="nav-item dropdown">-->
        <!--  <a class="nav-link active dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">-->
        <!--    Categories-->
        <!--  </a>-->
        <!--  <ul class="dropdown-menu dropdown-menu-dark" style="width: 220px; aria-labelledby="navbarDropdownMenuLink">-->
        <!--   {% for cats in categories %}-->
        <!--    <li><a class="dropdown-item d-flex gap-2 align-items-center" href="{{ cats.get_absolute_url }}">{{ cats.name |title }}</a></li>-->
        <!--   {% endfor %}-->
        <!--</ul>-->
        <!--</li>-->
    </div>
</div></ul>
        <!--<form class="d-flex">-->
            <!--<input class="form-control me-2 my-2" type="search" placeholder="Search" aria-label="Search">-->
                    <a type="button" role="button" href="{% url "cart:basket" %}" class="btn btn-outline-secondary border-0 basket-btn">
                        <div><div class="d-inline-flex text-white" id="basket-qty">0</div>
                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="#ffffff" class="bi bi-cart4" viewBox="0 0 16 16">
                        <path d="M0 2.5A.5.5 0 0 1 .5 2H2a.5.5 0 0 1 .485.379L2.89 4H14.5a.5.5 0 0 1 .485.621l-1.5 6A.5.5 0 0 1 13 11H4a.5.5 0 0 1-.485-.379L1.61 3H.5a.5.5 0 0 1-.5-.5zM3.14 5l.5 2H5V5H3.14zM6 5v2h2V5H6zm3 0v2h2V5H9zm3 0v2h1.36l.5-2H12zm1.11 3H12v2h.61l.5-2zM11 8H9v2h2V8zM8 8H6v2h2V8zM5 8H3.89l.5 2H5V8zm0 5a1 1 0 1 0 0 2 1 1 0 0 0 0-2zm-2 1a2 2 0 1 1 4 0 2 2 0 0 1-4 0zm9-1a1 1 0 1 0 0 2 1 1 0 0 0 0-2zm-2 1a2 2 0 1 1 4 0 2 2 0 0 1-4 0z"/>
                        </svg>
                        </div>
                        <span class="fs15 fw500 text-white"></span>
                    </a>

            {% if user.is_authenticated %}
            <button class="btn btn-nav mx-2 mt-1 px-5" type="submit">
            <a href="{% url 'accounts:logout' %}">Logout</a></button>
            {% else %}

             <button class="btn btn-nav mx-2 mt-1 me-2 py-2" type="submit">
             <a href="{% url 'accounts:login' %}">Login/Signup</button>
            </a>
             {% endif %}




</nav>
  </header>








  {% block content %}

  {% endblock %}



  <div class="footer fixed-bottom">
    <div class="container-fluid">
    <footer class="footer d-flex flex-wrap justify-content-between align-items-center pt-2 pb-3 px-3 mt-2 mx-0">
      <div class="col-md-4 d-flex align-items-center">
        <a href="/" class="mb-3 me-2 mb-md-0 text-muted text-decoration-none lh-1">
          <svg class="bi" width="30" height="24"><use xlink:href="#bootstrap"/></svg>
        </a>
        <span class="text-white">&copy; 2021 Pipeloluwa</span>
      </div>

      <ul class=" nav col-md-4 justify-content-end list-unstyled d-flex">
        <li class="ms-3"><a class="svg" href="https://pipeloluwadebayo.github.io/portfolio/"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="#ffffff" class="bi bi-person-circle" viewBox="0 0 16 16">
          <path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0z"/>
          <path fill-rule="evenodd" d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8zm8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1z"/>
        </svg></a></li>
        <li class="ms-3"><a class="svg" href="https://github.com/pipeloluwadebayo"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="#ffffff" class="bi bi-github" viewBox="0 0 16 16">
          <path d="M8 0C3.58 0 0 3.58 0 8c0 3.54 2.29 6.53 5.47 7.59.4.07.55-.17.55-.38 0-.19-.01-.82-.01-1.49-2.01.37-2.53-.49-2.69-.94-.09-.23-.48-.94-.82-1.13-.28-.15-.68-.52-.01-.53.63-.01 1.08.58 1.23.82.72 1.21 1.87.87 2.33.66.07-.52.28-.87.51-1.07-1.78-.2-3.64-.89-3.64-3.95 0-.87.31-1.59.82-2.15-.08-.2-.36-1.02.08-2.12 0 0 .67-.21 2.2.82.64-.18 1.32-.27 2-.27.68 0 1.36.09 2 .27 1.53-1.04 2.2-.82 2.2-.82.44 1.1.16 1.92.08 2.12.51.56.82 1.27.82 2.15 0 3.07-1.87 3.75-3.65 3.95.29.25.54.73.54 1.48 0 1.07-.01 1.93-.01 2.2 0 .21.15.46.55.38A8.012 8.012 0 0 0 16 8c0-4.42-3.58-8-8-8z"/>
        </svg></a></li>
        <li class="ms-3"><a class="svg" href="https://www.linkedin.com/in/pipeloluwa-adebayo-7b1222226/"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="#ffffff" class="bi bi-linkedin" viewBox="0 0 16 16">
          <path d="M0 1.146C0 .513.526 0 1.175 0h13.65C15.474 0 16 .513 16 1.146v13.708c0 .633-.526 1.146-1.175 1.146H1.175C.526 16 0 15.487 0 14.854V1.146zm4.943 12.248V6.169H2.542v7.225h2.401zm-1.2-8.212c.837 0 1.358-.554 1.358-1.248-.015-.709-.52-1.248-1.342-1.248-.822 0-1.359.54-1.359 1.248 0 .694.521 1.248 1.327 1.248h.016zm4.908 8.212V9.359c0-.216.016-.432.08-.586.173-.431.568-.878 1.232-.878.869 0 1.216.662 1.216 1.634v3.865h2.401V9.25c0-2.22-1.184-3.252-2.764-3.252-1.274 0-1.845.7-2.165 1.193v.025h-.016a5.54 5.54 0 0 1 .016-.025V6.169h-2.4c.03.678 0 7.225 0 7.225h2.4z"/>
        </svg></a></li>
        <li class="ms-3"><a class="svg" href="https:twitter.com/thatraregem"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="#ffffff" class="bi bi-twitter" viewBox="0 0 16 16">
          <path d="M5.026 15c6.038 0 9.341-5.003 9.341-9.334 0-.14 0-.282-.006-.422A6.685 6.685 0 0 0 16 3.542a6.658 6.658 0 0 1-1.889.518 3.301 3.301 0 0 0 1.447-1.817 6.533 6.533 0 0 1-2.087.793A3.286 3.286 0 0 0 7.875 6.03a9.325 9.325 0 0 1-6.767-3.429 3.289 3.289 0 0 0 1.018 4.382A3.323 3.323 0 0 1 .64 6.575v.045a3.288 3.288 0 0 0 2.632 3.218 3.203 3.203 0 0 1-.865.115 3.23 3.23 0 0 1-.614-.057 3.283 3.283 0 0 0 3.067 2.277A6.588 6.588 0 0 1 .78 13.58a6.32 6.32 0 0 1-.78-.045A9.344 9.344 0 0 0 5.026 15z"/>
        </svg></a></li>
      </ul>
    </footer>
  </div>
</div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
 <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
    -->
  </body>
</html>

templates/shop/category.html
{% extends 'shop/base.html' %}
{% block title %}
{{ cats.name }}
{% endblock %}
{% block content %}
<main>

    <div class="container pt-5 mb-5">
      <div class="row">
        <div class="album pt-0 pb-5 mb-5">
         <div class="container">
        <div class="pb-3 h3">{{ cats.name }}</div>
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 row-cols-lg-8 g-3">
       {% for product in products %}
       <div class="col">
            <div class="card border-0">
                <img <img "pt-3 home-img" width="100%" height="300"  src="{{ product.image.url }}">

            <div class="card-body px-2">
              <p class="card-text fw-bold">
                   <a class="text-dark text-decoration-none" href="{{ product.get_absolute_url }}">{{ product.title | title }}</a>
            </p>
              <div class="fw-bold">N {{product.price}}</div>
            </div>
          </div>
          </div>

        {% endfor %}
        </div>
        </div>
        </div>
        </div>


</main>





{% endblock %}

templates/shop/home.html
{% extends "../account/base.html" %}

{% block content %}

{% load basket %}
{% load custom_filter %}
<section class="pt-3 pb-1 text-center container pb-0">
    <div class="row py-lg-5">
        <div class="col-lg-6 col-md-8 mx-auto">
         {% if user.is_authenticated %}
             <h1 class="fw-bold">Welcome! {{ user.username | title}}
             </h1>
             <p class="lead text-muted">we are glad to have you back</p>
             {% else %}
             <h1 class="fw-bold">Welcome!
             </h1>

                <p class="lead text-muted">we are glad to have you</p>
                 {%  endif %}
        </div>
    </div>
</section>
<div class="container-fluid mt-3">
	<div class="row">
	    <div class="col-lg-3 mx-auto item">
			<div class="list-group ">
			    <a href="/" class="list-group-item list-group-item-action btn btn-outline-primary">All Products</a>

				{% for cats in categories %}
				<a href="{{ cats.get_absolute_url }}"
					class="list-group-item list-group-item-action btn btn-outline-primary ">{{ cats.name |title }}</a>
				{% endfor %}
			</div>
		</div>


		<div id='products' class="col-lg-9 mx-auto item">
			<div class="row mx-auto">
				{% for product in products %}
				<div class="card mx-auto mb-3 item"  style="width: 18rem;">
					<img class="pt-3 home-img" width="100%" height="300" src="{{product.image.url}}" alt="Product Image">
					<div class="card-body">
						<p class="card-text">{{product.title|title}}</p>
						<p class="card-text fw-bold"><b>N{{product.price}}</b></p>

					</div>

					<div class="card-footer p-0 no-gutters">


						<form action="{{ product.get_absolute_url }}" method="POST" class="btn-block">
							{% csrf_token %}
							<input hidden type="text" name='product' value='{{product.id}}'>
							<input type="submit" class="float-right btn btn-primary form-control mb-2"
								value="Add To Cart">
						</form>


					</div>

				</div>
				{% endfor %}
			</div>
		</div>
	</div>
</div>



{% endblock %}

templates/shop/index.html
{% extends 'shop/base.html' %}
{% block content %}
<main>
<section class="pt-3 pb-1 text-center container pb-0">
    <div class="row py-lg-5">
        <div class="col-lg-6 col-md-8 mx-auto">
         {% if user.is_authenticated %}
             <h1 class="fw-bold">Welcome! {{ user.username | title}}
             </h1>
             <p class="lead text-muted">we are glad to have you back</p>
             {% else %}
             <h1 class="fw-bold">Welcome!
             </h1>

                <p class="lead text-muted">we are glad to have you</p>
                 {%  endif %}
        </div>
    </div>
</section>
    <div class="container pt-0 mb-5">
      <div class="row">
        <div class="album pt-0 pb-5 mb-5">
         <div class="container">
        <div class="pb-3 h3">All Items</div>
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 row-cols-lg-8 g-3">
       {% for product in products %}
       <div class="col">
            <div class="card border-0">
                <img class="pt-3 home-img" width="100%" height="200"  src="{{ product.image.url }}">

            <div class="card-body px-2">
              <p class="card-text fw-bold">
                   <a class="text-dark text-decoration-none" href="{{ product.get_absolute_url }}">{{ product.title | title }}</a>
            </p>
              <div class="fw-bold">N {{product.price}}</div>
            </div>
          </div>
          </div>

        {% endfor %}
        </div>
        </div>
        </div>
        </div>
</main>


{% endblock %}

templates/shop/item.html
{% extends "shop/base.html" %}
{% block title %}
{{ product.name }}
{% endblock %}
{% block content %}
<section class="item">
<div class="container pt-5">
    <main class="pt-5">
        <div class="row g-3">
            <div class="col-md-5 col-lg-5 order-md-first bg-light py-3">
                <img class="img-fluid mx-auto d-block" width="200px" alt="Responsive image" src="{{ product.image.url }}">
            </div>
            <div class="col-md-7 col-lg-7 ps-md-3 ps-lg-5">
                <h1 class="mb-0 h4">{{ product.title | title }}</h1>
                <p>{{ product.description|slice:":355" }}...</p>
                <div class="border">
                    <div class="col border-bottom">
                        <div class="row p-3">
                            <div class="col-6">{{ product.title | title}}</div>
                            <div class="col-6 text-end"><span class="h4 fw-bold">N {{ product.price }}</span></div>
                        </div>
                    </div>
                    <div class="col">
                        <div class="row p-3">
                            <div class="col-6">
                   <div class="">
                                <label for="select">Qty</label>
                                <select id="select" class="h6" style="width:50px;height:40px;">
                                    <option value="1">1</option>
                                    <option value="2">2</option>
                                    <option value="3">3</option>
                                    <option value="4">4</option>
                                </select>
                    </div>
							</div>
							<div class="col-6 text-end"><a href="{% url 'cart:basket' %}"><button class="btn btn-secondary btn-other btn-sm" >
                                Add to Cart</button></a> </div>
                    </div>
                </div>
            </div>
        </div>
        <a href="{% url 'shop:store' %}">
            <button class="btn btn-other text-white mt-3" >Go Back</button>
        </a>
    </main>
</div>
</section>
<script>
    $(document).on('click', '#add-button', function (e) {
        e.preventDefault();
        $.ajax({
            type: 'POST',
            url: '{% url "cart:basket" %}',
            data: {
                productid: $('#add-button').val(),
                productqty: $('#select option:selected').text(),
                csrfmiddlewaretoken: "{{csrf_token}}",
                action: 'post'
            },
            success: function (json) {
              document.getElementById("basket-qty").innerHTML = json.qty
            },
            error: function (xhr, errmsg, err) {}
        });
    })
</script>

{% endblock %}